spring:
  application:
    name: consumer-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 10000