FROM openjdk:8-jre-alpine
COPY product-recipe-microservice.jar /opt/spring-cloud/lib/product-recipe-microservice.jar
ENTRYPOINT ["java", "-jar", "/opt/spring-cloud/lib/product-recipe-microservice.jar"]